name: best_flutter_app
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=3.2.5"
  flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter
  jivosdk_plugin: 0.9.2
  firebase_messaging: 14.8.0
  firebase_core: 2.28.0

dev_dependencies:
  flutter_lints: 3.0.2

flutter:
  uses-material-design: true
